directory_type = "workspace"

[workspace]
[[workspace.projects]]
path = "hooli-data-eng"

[[workspace.projects]]
path = "hooli-data-ingest"

[[workspace.projects]]
path = "hooli-bi"

[[workspace.projects]]
path = "hooli-basics"

[[workspace.projects]]
path = "hooli-snowflake-insights"

[[workspace.projects]]
path = "hooli-batch-enrichment"

# currently failing bc of strange import error or package versions
#[[workspace.projects]]
#path = "hooli-airlift"

[cli]
suppress_warnings = [
    "deprecated_dagster_dg_library_entry_point"
]