directory_type = "workspace"

# currently failing bc of strange import error or package versions
#[[workspace.projects]]
#path = "hooli-interoperability"


[[workspace.projects]]
path = "hooli-etl-pipeline"

[cli]
suppress_warnings = [
    "deprecated_dagster_dg_library_entry_point"
]
