directory_type = "workspace"

[workspace]
[[workspace.projects]]
path = "hooli-data-eng"


[[workspace.projects]]
path = "hooli-basics"

[[workspace.projects]]
path = "hooli-etl-pipeline"

# currently failing bc of strange import error or package versions
#[[workspace.projects]]
#path = "hooli-interoperability"


[cli]
suppress_warnings = [
    "deprecated_dagster_dg_library_entry_point"
]