# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under my_mlops_project/resources/*
# and my_mlops_project/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for my_mlops_project Staging

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./my_mlops_project

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: my_mlops_project-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.236.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t staging
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t staging
