attributes:
  job_name_prefix: databricks_mlops_pipeline
  serverless: true
  tasks:
  - asset_specs:
    - description: batch_inference_job from batch_inference_job job
      key: batch_inference_job
      kinds:
      - databricks
      - notebook
    notebook_path: /Users/${workspace.current_user.userName}/.bundle/${bundle.name}/${bundle.target}/files/deployment/batch_inference/notebooks/BatchInference.py
    parameters:
      env: '{{ env }}'
      git_source_info: url:{{ bundle_git.origin_url }}; branch:{{ bundle_git.branch
        }}; commit:{{ bundle_git.commit }}
      input_table_name: '{{ env }}.databricks_mlops.feature_store_inference_input'
      model_name: '{{ catalog_name }}.databricks_mlops.{{ model_name }}'
      output_table_name: '{{ catalog_name }}.databricks_mlops.predictions'
    task_key: batch_inference_job
  - asset_specs:
    - description: Train from model_training_job job
      key: train
      kinds:
      - databricks
      - notebook
    notebook_path: /Users/${workspace.current_user.userName}/.bundle/${bundle.name}/${bundle.target}/files/training/notebooks/TrainWithFeatureStore.py
    parameters:
      dropoff_features_table: '{{ catalog_name }}.databricks_mlops.trip_dropoff_features'
      env: '{{ env }}'
      experiment_name: '{{ experiment_name }}'
      git_source_info: url:{{ bundle_git.origin_url }}; branch:{{ bundle_git.branch
        }}; commit:{{ bundle_git.commit }}
      model_name: '{{ catalog_name }}.databricks_mlops.{{ model_name }}'
      pickup_features_table: '{{ catalog_name }}.databricks_mlops.trip_pickup_features'
      training_data_path: /databricks-datasets/nyctaxi-with-zipcodes/subsampled
    task_key: Train
  - asset_specs:
    - deps:
      - train
      description: ModelValidation from model_training_job job
      key: model_validation
      kinds:
      - databricks
      - notebook
    notebook_path: /Users/${workspace.current_user.userName}/.bundle/${bundle.name}/${bundle.target}/files/validation/notebooks/ModelValidation.py
    parameters:
      custom_metrics_loader_function: custom_metrics
      enable_baseline_comparison: 'false'
      evaluator_config_loader_function: evaluator_config
      experiment_name: '{{ experiment_name }}'
      git_source_info: url:{{ bundle_git.origin_url }}; branch:{{ bundle_git.branch
        }}; commit:{{ bundle_git.commit }}
      model_type: regressor
      run_mode: dry_run
      targets: fare_amount
      validation_input: SELECT * FROM delta.`dbfs:/databricks-datasets/nyctaxi-with-zipcodes/subsampled`
      validation_thresholds_loader_function: validation_thresholds
    task_key: ModelValidation
  - asset_specs:
    - deps:
      - model_validation
      description: ModelDeployment from model_training_job job
      key: model_deployment
      kinds:
      - databricks
      - notebook
    notebook_path: /Users/${workspace.current_user.userName}/.bundle/${bundle.name}/${bundle.target}/files/deployment/model_deployment/notebooks/ModelDeployment.py
    parameters:
      env: '{{ env }}'
      git_source_info: url:{{ bundle_git.origin_url }}; branch:{{ bundle_git.branch
        }}; commit:{{ bundle_git.commit }}
    task_key: ModelDeployment
  - asset_specs:
    - description: PickupFeatures from write_feature_table_job job
      key: pickup_features
      kinds:
      - databricks
      - notebook
    notebook_path: /Users/${workspace.current_user.userName}/.bundle/${bundle.name}/${bundle.target}/files/feature_engineering/notebooks/GenerateAndWriteFeatures.py
    parameters:
      features_transform_module: pickup_features
      git_source_info: url:{{ bundle_git.origin_url }}; branch:{{ bundle_git.branch
        }}; commit:{{ bundle_git.commit }}
      input_end_date: ''
      input_start_date: ''
      input_table_path: /databricks-datasets/nyctaxi-with-zipcodes/subsampled
      output_table_name: '{{ catalog_name }}.databricks_mlops.trip_pickup_features'
      primary_keys: zip
      timestamp_column: tpep_pickup_datetime
    task_key: PickupFeatures
  - asset_specs:
    - description: DropoffFeatures from write_feature_table_job job
      key: dropoff_features
      kinds:
      - databricks
      - notebook
    notebook_path: /Users/${workspace.current_user.userName}/.bundle/${bundle.name}/${bundle.target}/files/feature_engineering/notebooks/GenerateAndWriteFeatures.py
    parameters:
      features_transform_module: dropoff_features
      git_source_info: url:{{ bundle_git.origin_url }}; branch:{{ bundle_git.branch
        }}; commit:{{ bundle_git.commit }}
      input_end_date: ''
      input_start_date: ''
      input_table_path: /databricks-datasets/nyctaxi-with-zipcodes/subsampled
      output_table_name: '{{ catalog_name }}.databricks_mlops.trip_dropoff_features'
      primary_keys: zip
      timestamp_column: tpep_dropoff_datetime
    task_key: DropoffFeatures
template_vars_module: .get_env
type: hooli_ml.components.DatabricksMultiNotebookJobComponent
