[project]
name = "hooli_data_eng"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
      "dagster",
      "dagster-dbt",
      "dagster-cloud",
      "dbt-core",
      "dbt-duckdb",
      "dbt-snowflake",
]
