version: 2

models:
  - name: orders_cleaned
    config:
      meta:
        dagster:
            owners: ["nelson.bighetti@hooli.com", "team:data@hooli.com"]
    # group: marketing-group
    # config:
    #   alias: orders_something_else
    description: "Cleaned version of raw orders data"
    columns:
      - name: user_id
        description: "Platform id of the user that placed this order."
        data_type: "int"
        tests:
          - not_null
      - name: quantity
        description: "The quantity of items purchased in this order."
      - name: purchase_price
        description: "The price of this item at the time the user placed the order."
        data_type: "float"
      - name: sku
        description: "The identifier of the item purched in this order."
        data_type: "str"
      - name: dt
        description: "The UTC time when this order was placed."
        data_type: "timestamp"
      - name: date
        description: "The UTC day when this order was placed."
        data_type: "timestamp"
      - name: order_total
        description: "The total purchase price for this order"
        data_type: "float"
        tests:
          - greater_than_zero:
              config:
                alias: testing_alias

  - name: users_cleaned
    # group: core-data-eng
    description: "Raw users data with test accounts removed"
    config:
      tags: "core_kpis"
    columns:
      - name: "user_id"
        description: "Platform id of the user."
        data_type: "int"
      - name: "company"
        description: "The name of the company that this user belongs to."
        data_type: "str"
        tests:
          - dbt_expectations.expect_column_values_to_match_like_pattern_list:
              like_pattern_list: ["%Sport%","%Co%","%Ltd%", "%Shop%"]
              match_on: any # (Optional. Default is 'any', which applies an 'OR' for each pattern. If 'all', it applies an 'AND' for each regex.)
              alias: example_alias
      - name: "created_at"
        description: "When the user account was crated"
        data_type: "timestamp"

  - name: locations_cleaned
    description: "Locations data with standardized column names"
    columns:
      - name: "user_id"
        description: "The unique identifier for the user"
        data_type: "int"
      - name: "street_address"
        description: "The user's street address"
        data_type: "str"
      - name: "state"
        description: "The state portion of the user's address"
        data_type: "str"
      - name: "country"
        description: "The unique identifier for the user"
        data_type: "str"
      - name: "zip_code"
        description: "The user's street address"
        data_type: "str"
      - name: "_sling_loaded_at"
        description: "The state portion of the user's address"
        data_type: "int"
