jdbt:
  target: LOCAL
  outputs:
    LOCAL:
      type: duckdb
      path: /tmp/jaffle_platform.duckdb
      schema: analytics
      threads: 1

    PROD:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', '') }}"
      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER', '') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', '') }}"
      database: DEMO_DB2
      warehouse: TINY_WAREHOUSE
      schema: analytics
      client_session_keep_alive: False

    BRANCH:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', '') }}"
      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER', '') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', '') }}"
      database: DEMO_DB2_BRANCH
      warehouse: TINY_WAREHOUSE
      schema: analytics
      client_session_keep_alive: False