name: Preview Dagster Cloud Pipelines
on: [pull_request]

jobs:
  dagster-cloud-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cache Docker builds
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Run Dagster Cloud CI action
        uses: dagster-io/dagster-cloud-cicd-action/preview@v0.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dagit-url: https://hooli.dagster.cloud/data-eng-prod
          api-token: ${{ secrets.DAGSTER_AGENT_TOKEN }}

      - name: Prune unused layers
        run: docker image prune -a -f --filter="label!=sha=${{ github.sha }}"
